"""Update UserUpdate schema

Revision ID: 04172cdadd04
Revises: f3a0ab0c0ddb
Create Date: 2025-08-01 18:34:30.353714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04172cdadd04'
down_revision: Union[str, Sequence[str], None] = 'f3a0ab0c0ddb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
