"""update google_credentials model

Revision ID: 6f9f6835eaf3
Revises: db03611e99a1
Create Date: 2025-08-07 15:15:29.644376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f9f6835eaf3'
down_revision: Union[str, Sequence[str], None] = 'db03611e99a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_google_credentials_created_at'), 'google_credentials', ['created_at'], unique=False)
    op.create_index(op.f('ix_google_credentials_id'), 'google_credentials', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_google_credentials_id'), table_name='google_credentials')
    op.drop_index(op.f('ix_google_credentials_created_at'), table_name='google_credentials')
    op.drop_table('google_credentials')
    # ### end Alembic commands ###
