"""Update DateTime timezone fields

Revision ID: f3a0ab0c0ddb
Revises: 9f458233b0e8
Create Date: 2025-08-01 16:47:01.789155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3a0ab0c0ddb'
down_revision: Union[str, Sequence[str], None] = '9f458233b0e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
